name: Build Docker Image

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - '.github/**'
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  run:
    name: "Build Docker Image"
    runs-on: latest

    steps:
      - uses: action/checkout@v4
