name: test wf summary

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run fail script
        id: fail
        run: ./scripts/failure.sh

      - name: Run pass script
        id: pass
        run: ./scripts/sucess.sh
